[core]
retries = 5
plugins = "resources/plugins"

[[server]]
name = "freenode"
hostname = "irc.freenode.net"
port = 6697

[[server]]
name = "gamesurge"
hostname = "irc.gamesurge.net"
port = 6697

[plugins.wiki]
setting = 500
whatever = "okay"
